"""stage order id in delivery table

Revision ID: 46fe802c92e9
Revises: a6c738797ecb
Create Date: 2016-11-07 16:18:52.313464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fe802c92e9'
down_revision = 'a6c738797ecb'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('delivery_orders', sa.Column('staging_order_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_orders', 'staging_order_id')
    ### end Alembic commands ###
