"""First auto-generation of db from models

Revision ID: 7ef1e44e41b7
Revises: 
Create Date: 2016-11-07 11:08:23.142336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ef1e44e41b7'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('delivery_source', sa.String(), nullable=False),
    sa.Column('delivery_project', sa.String(), nullable=False),
    sa.Column('delivery_status', sa.Enum('delivery_failed', 'delivery_in_progress', 'delivery_finished', 'pending', name='deliverystatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staging_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'staging_failed', 'staging_in_progress', 'staging_successful', name='stagingstatus'), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staging_orders')
    op.drop_table('delivery_orders')
    ### end Alembic commands ###
